name: pub_cache
version: 0.3.1
description: A library to reflect on the local pub cache.
homepage: https://github.com/google/pub_cache

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  pub_semver: ^2.0.0
  yaml: ^3.0.0

dev_dependencies:
  test: ^1.16.4
